swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "orders-app.endpoints.cloud-code-demo-360914.cloud.goog"
x-google-endpoints:
- name: "orders-app.endpoints.cloud-code-demo-360914.cloud.goog"
  target: "34.107.173.123"
