apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-worker
  labels:
    app: orders
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
      tier: worker
  template:
    metadata:
      labels:
        app: orders
        tier: worker
    spec:
      containers:
      - name: worker
        image: us-east1-docker.pkg.dev/cloud-code-demo-360914/repo/orders-worker:latest
        ports:
        - name: debug
          containerPort: 3000
        env:
        - name: SPANNER_URI
          value: "projects/cloud-code-demo-360914/instances/nick-spanner/databases/nickdb"
        - name: APP_PORT
          value: "8080"