# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: job
build:
  artifacts:
  - image: orders-job
    context: .
    # sync:
    #   infer:
    #     - '/**/*.go'
    #     - 'web/*.html'
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
# portForward:
#   # Cloud Code automatically port forwards resources,
#   # or users can define explicit port forwards here.
#   # For more info, visit https://skaffold.dev/docs/pipeline-stages/port-forwarding/#UDPF
#   - resourceType: Deployment
#     resourceName: orders-job
#     port: 80
#     localPort: 8080
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
    