apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-frontend
  labels:
    app: orders
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
      tier: frontend
  template:
    metadata:
      labels:
        app: orders
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: orders-frontend
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 3000
        env:
        - name: APP_PORT
          value: "8080"
        - name: SPANNER_URI
          value: "projects/cloud-code-demo-360914/instances/nick-spanner/databases/nickdb"