apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: orders-frontend
    context: .
    sync:
      infer:
      - /**/*.go
      - web/*.html
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
portForward:
- resourceType: service
  resourceName: orders-frontend
  port: 80
  localPort: 8080
profiles:
- name: cloudbuild
  build:
    local: {}
